version: '3.8'

services:
  fastapi:
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file: .env.dev
    container_name: fastapi_dev
    volumes:
      - ./app:/app
      - ./initdb.sql:/initdb.sql:ro
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      - sqlite_loader

  sqlite_loader:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: sqlite_loader
    volumes:
      - ./app:/app
      - ./initdb.sql:/initdb.sql:ro
    command: ["/load_sqlite3.sh"]
    restart: "no"

  sqliteweb:
    image: coleifer/sqlite-web
    container_name: sqlite_web_admin
    volumes:
      - ./app:/data
    ports:
      - "8081:8080"
    entrypoint: ["sqlite_web", "--host", "0.0.0.0", "/data/db.sqlite3"]
