version: '3.8'

services:
  fastapi:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env.dev
    container_name: fastapi_dev
    volumes:
      - ./app:/app
      - ./initdb.sql:/initdb.sql:ro
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped