version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: fastapi_prod
    env_file: .env.prod
    volumes:
      - ./app/media:/app/media
      - ./certs:/certs
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy
      cert_generator:
        condition: service_completed_successfully
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: postgres_prod
    restart: unless-stopped
    env_file: .env.prod
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}    
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb.prod.sql:/docker-entrypoint-initdb.d/initdb.prod.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DATABASE_USER -d $DATABASE_DB"]
      interval: 5s
      timeout: 5s
      retries: 5      
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_prod
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}admin@example.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  cert_generator:
    image: alpine/openssl:3.5.0
    container_name: cert_generator
    volumes:
      - ./certs:/certs
      - ./cert_gen.sh:/cert_gen.sh:ro
    entrypoint: ["sh", "/cert_gen.sh"]
    restart: "no"

volumes:
  postgres_data:
  pgadmin_data: