FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y openssl nano sudo && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app /app/

COPY cert_gen.sh /cert_gen.sh
RUN chmod +x /cert_gen.sh

COPY entrypoint_prod.sh /entrypoint_prod.sh
RUN chmod +x /entrypoint_prod.sh

ENV PYTHONUNBUFFERED=1

ENTRYPOINT ["/entrypoint_prod.sh"]
CMD ["python", "run.py"]