version: '3.8'

services:
  fastapi:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: fastapi_dev
    volumes:
      - .:/app               # Montuje kod źródłowy (hot-reload)
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped