FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y openssl sqlite3 nano sudo && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app /app/

COPY cert_gen.sh /cert_gen.sh
RUN chmod +x /cert_gen.sh

COPY load_sqlite3.sh /load_sqlite3.sh
RUN chmod +x /load_sqlite3.sh

COPY entrypoint_dev.sh /entrypoint_dev.sh
RUN chmod +x /entrypoint_dev.sh

ENV PYTHONUNBUFFERED=1

ENTRYPOINT ["/entrypoint_dev.sh"]
CMD ["python", "run.py"]