version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: fastapi_prod
    env_file: .env.prod
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: postgres_prod
    restart: unless-stopped
    env_file: .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: